version: '3.8'

services:
  scraper:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - BROWSER_WS=${BROWSER_WS}
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
